name: wordle

services:
  backend:
    image: wordle-backend:${RELEASE_TAG:-local}
    build:
      target: backend
    ports:
      - 3000:3000

  frontend:
    image: wordle:${RELEASE_TAG:-local}
    build:
      target: frontend
      args:
        - BASE_URL=/
    ports:
      - 5173:80
    environment:
      - VITE_API_URL=http://backend:3000/
