version: '3'

services:
  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts/initdb:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=wordle
      - POSTGRES_USER=wordle

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile

volumes:
  db-data:
